# Generated by Django 5.0.2 on 2024-03-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_imovel_contratolocacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratolocacao',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
