# Generated by Django 5.0.2 on 2024-03-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contratolocacao_nome_imovel_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratolocacao',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contratolocacao',
            name='valor_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
