# Generated by Django 5.0.2 on 2024-03-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_contratolocacao_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratolocacao',
            name='nome',
        ),
    ]
