# Generated by Django 5.0.2 on 2024-03-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_contratolocacao_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratolocacao',
            options={'verbose_name_plural': 'Contratos de Locação'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name_plural': 'Imoveis'},
        ),
        migrations.AddField(
            model_name='contratolocacao',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
